org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=1.21.11
loader_version=0.18.6
loom_version=1.15.5
yarn_mappings=1.21.11+build.4
mod_version=1.0.0
maven_group=com.dimexhits
archives_base_name=dimensional-explosive-hits
fabric_api_version=0.141.3+1.21.11
